### ISSUE TITLE
Error in creating NSX-T Transport Node Profile

### ISSUE THREAD

**Issue by ssaksa80** [lamw/vsphere-with-tanzu-nsxt-automated-lab-deployment#29]
I am not able to fix the issue, any tips to fix it

[11-14-2022_09:38:31] Creating ESXi Uplink Profile ...
[11-14-2022_09:38:31] Creating Edge Uplink Profile ...
[11-14-2022_09:38:32] Creating Transport Node Profile Tanzu-Host-Transport-Node-Profile ...
Write-Error: Error in creating NSX-T Transport Node Profile
Write-Error:
({
  "httpStatus" : "BAD_REQUEST",
  "error_code" : 9538,
  "module_name" : "NsxSwitching service",
  "error_message" : "Cannot find the HostSwitch [50 3a ea 97 aa a8 23 0a-42 bf 57 e9 32 b1 65 ff] of type VDS."
}.Exception.Message)

**Comment by rexit1982** [comment]
Edit line 1208 to read "resource_type" = "TransportNodeProfile"; instead of "resource_type" = "TransportNode";
