### ISSUE TITLE
$ESXiUplinkProfileTransportVLAN variable declaration missing 

### ISSUE THREAD

**Issue by tigerhawk6** [lamw/vsphere-with-tanzu-nsxt-automated-lab-deployment#7]
I needed to add the following to the "Uplink Profiles" section to get NSX-T to work for me. I added it at line 113 and defined it. It's already being added to the Profile Spec at line 1062

$ESXiUplinkProfileTransportVLAN = ""

**Comment by lamw** [comment]
This has been fixed
